name: runner-test
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Show podman info
      run: |
        podman info
        find /etc/containers -type f -exec cat {} \;
        cat /etc/systemd/journald.conf

    - uses: actions/checkout@v3

    - name: Build image
      run: make build
    
    - name: Small test
      run: |
        make test
        SIZE=10000 make test

    - name: Big test
      timeout-minutes: 1
      run: SIZE=200000 make test

    - name: Inspect
      if: failure()
      run: |
        mkdir -p container-logs
        for c in $(podman ps --filter name=test- --format'{{.Names}}'); do
          podman logs ${c} > container-logs/${c}.log
          podman inspect ${c} > container-logs/${c}_inspect.log
        done

    - name: Create artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: container-logs
        path: container-logs/
